
package client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DCMSService", targetNamespace = "http://service.server/", wsdlLocation = "file:/G:/XieRongEclipse/workspace/DcmsWebService/wsdl/DCMSService.wsdl")
public class DCMSService
    extends Service
{

    private final static URL DCMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DCMSSERVICE_EXCEPTION;
    private final static QName DCMSSERVICE_QNAME = new QName("http://service.server/", "DCMSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/G:/XieRongEclipse/workspace/DcmsWebService/wsdl/DCMSService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DCMSSERVICE_WSDL_LOCATION = url;
        DCMSSERVICE_EXCEPTION = e;
    }

    public DCMSService() {
        super(__getWsdlLocation(), DCMSSERVICE_QNAME);
    }

    public DCMSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DCMSSERVICE_QNAME, features);
    }

    public DCMSService(URL wsdlLocation) {
        super(wsdlLocation, DCMSSERVICE_QNAME);
    }

    public DCMSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DCMSSERVICE_QNAME, features);
    }

    public DCMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DCMSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DCMS
     */
    @WebEndpoint(name = "DCMSPort")
    public DCMS getDCMSPort() {
        return super.getPort(new QName("http://service.server/", "DCMSPort"), DCMS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DCMS
     */
    @WebEndpoint(name = "DCMSPort")
    public DCMS getDCMSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.server/", "DCMSPort"), DCMS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DCMSSERVICE_EXCEPTION!= null) {
            throw DCMSSERVICE_EXCEPTION;
        }
        return DCMSSERVICE_WSDL_LOCATION;
    }

}
